# Generated by Django 4.0 on 2022-09-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=255, verbose_name='Track Name')),
                ('n_citacoes', models.PositiveIntegerField()),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=999)),
                ('prime_genre', models.CharField(max_length=30, verbose_name='App Genre')),
            ],
            options={
                'db_table': 'metric',
            },
        ),
    ]
