# Generated by Django 4.0 on 2022-09-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric', '0002_alter_metric_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='n_citacoes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='metric',
            name='size_bytes',
            field=models.BigIntegerField(),
        ),
    ]
