# Generated by Django 4.0 on 2022-09-27 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metric', '0003_alter_metric_n_citacoes_alter_metric_size_bytes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DateTimeField(auto_now_add=True, verbose_name='hours')),
                ('metric_id', models.ForeignKey(db_column='metric_id', on_delete=django.db.models.deletion.PROTECT, to='metric.metric', verbose_name='Metric')),
            ],
        ),
    ]
