# Generated by Django 4.0 on 2022-09-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric', '0004_logmetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmetric',
            name='hours',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='hours'),
        ),
    ]
