# Generated by Django 4.0 on 2022-09-27 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metric', '0005_alter_logmetric_hours'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logmetric',
            table='log_metric',
        ),
    ]
