# Generated by Django 4.0 on 2022-09-27 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric', '0005_alter_logmetric_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmetric',
            name='hours',
            field=models.CharField(default=datetime.datetime(2022, 9, 27, 0, 49, 38, 4752), max_length=194, verbose_name='hours'),
        ),
    ]
